### ISSUE TITLE
Container must be run with group "root" to update passwd file

### ISSUE THREAD

**Issue by franckalbinet** [mimoralea/gdrl#1]
Hi Miguel,

Thanks for today's update with the new fresh chapter 5. I am trying to install everything via Docker.

When running  `
docker run -it --rm -p 8888:8888 -v "$PWD"/notebooks/:/mnt/notebooks/ mimoralea/gdrl:v0.7`,  then accessing Jupyter, the password you provided looks invalid.

Furthermore, the first line in the console line after running the container is:
```
Container must be run with group "root" to update passwd file
```
Am I missing something? 

Thanks again

**Comment by mimoralea** [comment]
Hi, Franck.

I'm not sure what the problem would be. I just run the steps above, downloaded the image on a clean system, input the password `gdrl` and I'm able to access the chapters.

I wonder if the issue is that the repository was cloned with different group permissions?

Can you show me the permissions you have? Do your user and group seem to have the correct permissions?

```bash
± |master ✓| → ls -la notebooks/chapter_05
total 3200
drwxr-xr-x   3 mimoralea  staff       96 Feb 16 12:48 .
drwxr-xr-x  11 mimoralea  staff      352 Feb 16 12:48 ..
-rw-r--r--   1 mimoralea  staff  1635282 Feb 16 12:48 chapter-05.ipynb
```

**Comment by franckalbinet** [comment]
Thx for your quick reply!

I do have the same permissions as you:

```
ganesh:gdrl-official-repo franck$ ls -la notebooks/chapter_05                                    │
total 3200                                                                                       │
drwxr-xr-x   3 franck  staff      102 Feb 16 18:35 .                                             │
drwxr-xr-x  12 franck  staff      408 Feb 16 21:54 ..                                            │
-rw-r--r--   1 franck  staff  1635282 Feb 16 18:35 chapter-05.ipynb  
```
Just wanted to check with you in case I missed something obvious. I will continue investigating this issue after the we. Will keep you posted. Nothing urgent on my side.

Thx

**Comment by franckalbinet** [comment]
Simply stopped all other running Jupyter notebooks and that's it!  Get access to your amazing notebooks now. Thanks. Sorry for the inconvenience.

**Comment by mimoralea** [comment]
Great! Thanks for the feedback, Franck. And no worries, feel free to open issues at any time.

**Comment by yashGuleria** [comment]
Hi @franckalbinet , @mimoralea ,
3 years later, Im facing a similar problem. I have the permissions, No other notebook is open but still the the link for the jupyter notebook cannot be opened. Any suggestions?
![Screenshot from 2022-08-19 11-57-50](https://user-images.githubusercontent.com/43232867/185540324-8224bd3e-106b-4ae3-afa4-c15d35e836fc.png)
![Screenshot from 2022-08-19 12-02-45](https://user-images.githubusercontent.com/43232867/185540459-616ca7cc-656c-402f-8e82-d73e78f256ca.png)

**Comment by mimoralea** [comment]
Does localhost:8888/ work for you?

**Comment by yashGuleria** [comment]
Hi ! while starting the container I ran it with " sudo docker" instead of just "docker run . . .. " . And yes localhost:8888 worked. Thank you .
Regards

**Comment by cbasile2** [comment]
Hi Miguel , do I need to write grld somewhere? I am currently doing

 sudo docker run -it --rm -p 8888:8888 -v "$PWD"/notebooks/:/mnt/notebooks/ mimoralea/gdrl:v0.14

But, both the local , and nor the link generated worked. Should I replace PWD with grld?  Thanks

**Comment by mimoralea** [comment]
PWD prints the working directory. gdrl is the password to access the notebook through the website. First, make sure you're running these commands from the right folder

**Comment by cbasile2** [comment]
Hi Miguel , 

thanks. I am running from grld.  Here is the terminal shots.

![image](https://user-images.githubusercontent.com/4418146/198028562-95f8c210-c078-4b84-9026-0012d222ac2e.png)

![image](https://user-images.githubusercontent.com/4418146/198028665-80515ca4-0db3-4c6f-a6e9-91f9803b48a4.png)

Thanks

**Comment by cbasile2** [comment]
I run command from grld, and then it says is running , but when I go to local url I do not see it. Do I need to write grld password somewhere if I am running the terminal? I am new to docker. many thanks

**Comment by mimoralea** [comment]
Just open a browser and go to http://localhost:8888/ you will be asked for
a password there. Don't kill the terminal session, you need it running
while working.

Also notice it's gdrl, not grdl.

**Comment by cbasile2** [comment]
Miguel, wow now it worked. I actually had a local anaconda running already, and when I shut down my anaconda instance locally , then it worked. it will be nice to find out a way to have both your book and my own instance, I will try it smoe time later, but thanks for the help appreciate it!!
