### ISSUE TITLE
Cannot start the notebooks from the container

### ISSUE THREAD

**Issue by Spampi626** [mimoralea/gdrl#16]
Hi! First time opening an issue, hope to make it right.
Not a super expert of using Docker and Windows command line in general, but I followed the instruction on the README.
Basically, if I try to run the docker with the recommended command I get the error:

```
...\gdrl>docker run -it --rm -p 8888:8888 -v %CD%/notebooks/:/mnt/notebooks/ mimoralea/gdrl:v0.14
docker: invalid reference format: repository name must be lowercase.
See 'docker run --help'.
```

the same if I use %cd% instead of %CD%. 

I really don't understand where the issue is, since apart from %CD% there is no a single upper case letter.

**Comment by boyko11** [comment]
Hi @Spampi626,
I'd try putting quotes around "%CD%/notebooks/:/mnt/notebooks/".
If this doesn't help, I'd try putting the notebooks in a directory whose
full path doesn't have any spaces or any upper case letters. If that
doesn't help, there's various reasons for this error discussed here :
https://stackoverflow.com/questions/48522615/docker-error-invalid-reference-format-repository-name-must-be-lowercase

**Comment by Spampi626** [comment]
Thank you @boyko11 !
I had a directory with a space, I renamed it and it worked. 
Actually I had to upload manually the notebooks once inside jupyter, but everything else worked fine.
