### ISSUE TITLE
Formula/code discrepancy in Chapter 4?

### ISSUE THREAD

**Issue by steveant** [mimoralea/gdrl#18]
Really loving this book!! Doing plenty of reading and re-reading not to miss a beat.

I noticed a formula vs. code discrepancy in Chapter 4 - Upper Confidence Bound (UCB) equation formula where hyperparameter 'c' is outside the square root in the equation:
![image](https://user-images.githubusercontent.com/1930466/149848184-99ea278f-f2c3-4586-9f88-d29e6157bf7d.png)

but inside the square root in the code:
![image](https://user-images.githubusercontent.com/1930466/149848227-86a40ee3-b58f-4b4e-b8b8-40a1c7acc66d.png)

**Comment by mimoralea** [comment]
Hey, @steveant. Great find! Have you tested the code with the `c` outside the `sqrt`? That should be the correct implementation!
