### ISSUE TITLE
Docker run on windows fails, wrong syntax in readme?

### ISSUE THREAD

**Issue by h3xh3xh3x** [mimoralea/gdrl#27]
I ran your docker instructions for windows given in readme.md:
` docker run -it --rm -p 8888:8888 -v %CD%/notebooks/:/mnt/notebooks/ mimoralea/gdrl:v0.14`
After downloading all the files, it says:
`Status: Downloaded newer image for mimoralea/gdrl:v0.14
docker: Error response from daemon: create %CD%/notebooks: "%CD%/notebooks" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.`
It appears there is something wrong with the syntax.

The command runs well when '%CD%' is replaced with '.', however the notebook list is empty.

**Comment by mimoralea** [comment]
Don't have windows, so I can't test... let me know if you find a solution. The point is to pass the path to the `notebooks` directory.
