### ISSUE TITLE
a consistent requirements.txt needed

### ISSUE THREAD

**Issue by TwoDeen** [mimoralea/gdrl#35]
where can I find a consistent requirements.txt for this python code?
i'm running into numerous compatibility issues of libraries when I try and run the code.

**Comment by mimoralea** [comment]
The only supported dev environment is the docker container for simplicity.

https://github.com/mimoralea/gdrl?tab=readme-ov-file#running-the-code

**Comment by TwoDeen** [comment]
I tried docker and got the following, looks like it's suspended and I'm stuck.

Docker container is running but when pointing to localhost:8888 nothing happens.
I get the Docker warning "Image may have poor performance or fail, if run via emulation"
(btw I'm using a Mac Mini M2-Pro Apple Silicon running Mac OS Sonoma 14.2.1 and Docker 4.26)

`> docker run -it --rm -p 8888:8888 -v "$PWD"/notebooks/:/mnt/notebooks/ mimoralea/gdrl:v0.14
````
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
[TrustNotebookApp] Writing notebook-signing key to /home/jovyan/.local/share/jupyter/notebook_secret
Signing notebook: /mnt/notebooks/chapter_08/chapter-08.ipynb
Signing notebook: /mnt/notebooks/chapter_06/chapter-06.ipynb
Signing notebook: /mnt/notebooks/chapter_07/chapter-07.ipynb
Signing notebook: /mnt/notebooks/chapter_09/chapter-09.ipynb
Signing notebook: /mnt/notebooks/chapter_12/chapter-12.ipynb
Signing notebook: /mnt/notebooks/chapter_05/chapter-05.ipynb
Signing notebook: /mnt/notebooks/chapter_02/chapter-02.ipynb
Signing notebook: /mnt/notebooks/chapter_03/chapter-03.ipynb
Signing notebook: /mnt/notebooks/chapter_04/chapter-04.ipynb
Signing notebook: /mnt/notebooks/chapter_10/chapter-10.ipynb
Signing notebook: /mnt/notebooks/chapter_11/chapter-11.ipynb
```
