### ISSUE TITLE
"Spin up a container" correction

### ISSUE THREAD

**Issue by wmeitzen** [mimoralea/gdrl#5]
In your main document (README.md) / "Running the code" / "Spin up a container" / on Windows:

`docker run -it --rm -p 8888:8888 -v %cd%/notebooks/:/mnt/notebooks/ mimoralea/gdrl:v0.14`

The %cd% should be capitalized.  So, ...

`docker run -it --rm -p 8888:8888 -v %CD%/notebooks/:/mnt/notebooks/ mimoralea/gdrl:v0.14`

**Comment by mimoralea** [comment]
Thanks for this William. Do you want to contribute the pull request? I can't test it, but it makes sense.

**Comment by wmeitzen** [comment]
I'd rather not contribute at this time, thank you!

**Comment by mimoralea** [comment]
No worries. I made the change. Thanks for reporting.
