### ISSUE TITLE
Creating Notebook Failed

### ISSUE THREAD

**Issue by Hari-Krishna-QmFuZGk** [mimoralea/gdrl#6]
I entered password: "gdrl" at jupyter login link in my browser,  then after it showing notebook list empty and i can't even able to create new python notebook .ipynb file, returning a pop up block with error "Permission denied: Untitled.ipynb".
![Docker error](https://user-images.githubusercontent.com/66151651/91206153-4f177e00-e724-11ea-933d-24102406d8ca.JPG)

**Comment by mimoralea** [comment]
I haven't added an "Untitled.ipynb". Make sure you are pointing to the right folder when you start docker.
